baseurl = "http://www.paulobatista.ml/tpp-compiler/"
languageCode = "en-us"
title = "My New Hugo Site"
theme = "hugo-theme-learn"
[params]
# change default color scheme with a variant one
themeVariant = "green"
